name: Build & Upload

on:
  workflow_dispatch:
    inputs:
      build-all-spigot:
        description: 'Build all Spigot'
        type: boolean
      cache-buildtools-spigot-artifacts:
        description: 'Cache built Spigot artifacts'
        type: boolean

jobs:
  build:
    name: Build and Upload
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Check-out
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.checkout_ref }}
          fetch-depth: 0

      - name: Setup Azul Zulu JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          java-package: 'jdk'
          distribution: 'zulu'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          add-job-summary: 'never'
          cache-overwrite-existing: true
          gradle-version: "9.0.0"

      - name: Restore BuildTools & Spigot Artifacts
        uses: actions/cache/restore@v4
        with:
          path: |
            ~/.gradle/caches/build-tools/apache-maven-*
            ~/.gradle/caches/build-tools/BuildData
            ~/.gradle/caches/build-tools/Bukkit
            ~/.gradle/caches/build-tools/CraftBukkit
            ~/.gradle/caches/build-tools/metadata
            ~/.gradle/caches/build-tools/Spigot
            ~/.gradle/caches/build-tools/BuildTools.jar
            ~/.m2/repository/org/spigotmc
          key: buildtools-spigot-artifacts

      - name: Fix Spigot some builds
        if: ${{ inputs.build-all-spigot }}
        run: |
          mkdir -p ~/.m2/repository/org/spigotmc/minecraft-server/
          cp -rv ~/work/EasyPayments/EasyPayments/buildSrc/src/main/resources/buildtools/minecraft-server/* ~/.m2/repository/org/spigotmc/minecraft-server/

      - name: Build all Spigot
        if: ${{ inputs.build-all-spigot }}
        run: ./gradlew buildAllSpigot --no-daemon --stacktrace

      - name: Cache BuildTools & Spigot Artifacts
        if: always() && inputs.cache-buildtools-spigot-artifacts
        uses: actions/cache/save@v4
        with:
          path: |
            ~/.gradle/caches/build-tools/apache-maven-*
            ~/.gradle/caches/build-tools/BuildData
            ~/.gradle/caches/build-tools/Bukkit
            ~/.gradle/caches/build-tools/CraftBukkit
            ~/.gradle/caches/build-tools/metadata
            ~/.gradle/caches/build-tools/Spigot
            ~/.gradle/caches/build-tools/BuildTools.jar
            ~/.m2/repository/org/spigotmc
          key: buildtools-spigot-artifacts

      - name: Build with Gradle
        run: ./gradlew clean build -PbuildSpigot=all --no-daemon

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: EasyPayments
          path: build/EasyPayments-*.jar
          if-no-files-found: warn
